name: Terraform CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.0   # or whichever version you use

      - name: Terraform Init
        working-directory: Day-2-basic-code-tfvars
        run: terraform init

      - name: Terraform Plan
        working-directory: Day-2-basic-code-tfvars
        run: terraform plan
